import { Beach } from '@/types/beach';

const GITHUB_BASE_URL = 'https://raw.githubusercontent.com/Dex589/beach_photos/main/';

const IMAGE_MAPPING: Record<string, string> = {
  'amelia-island': '1-amelia-island.jpg',
  'anna-maria-island': '2-anna-maria-island.jpg',
  'asbury-park': '3-asbury-park.jpg',
  'assateague-island': '4-assateague-island.jpg',
  'atlantic-city': '5-atlantic-city.jpg',
  'avon-nc': '7-avon.jpg',
  'bal-harbour': '8-bal-harbour.jpg',
  'bandon-beach': '9-bandon-beach.jpg',
  'bar-harbor': '10-bar-harbor.jpg',
  'barnegat-light': '11-barnegat-light.jpg',
  'beach-haven': '12-beach-haven.jpg',
  'belleair-beach': '13-belleair-beach.jpg',
  'belmar': '14-belmar.jpg',
  'bethany-beach': '15-bethany-beach.jpg',
  'big-pine-key': '17-big-pine-key.jpg',
  'biloxi-beach': '18-biloxi-beach.jpg',
  'block-island': '19-block-island.jpg',
  'boca-grande': '20-boca-grande.jpg',
  'bolivar-peninsula': '21-bolivar-peninsula.jpg',
  'bonita-springs': '22-bonita-springs.jpg',
  'bradley-beach': '23-bradley-beach.jpg',
  'brant-beach': '24-brant-beach.jpg',
  'brookings-beach': '25-brookings-beach.jpg',
  'brownsville-beach': '26-brownsville-beach.jpg',
  'buxton': '27-buxton.jpg',
  'caladesi-island': '28-caladesi-island.jpg',
  'cannon-beach': '29-cannon-beach.jpg',
  'cape-cod': '30-cape-cod-national-seashore.jpg',
  'cape-hatteras': '31-cape-hatteras.jpg',
  'cape-may': '32-cape-may.jpg',
  'capitola-beach': '33-capitola-beach.jpg',
  'captiva-island': '34-captiva-island.jpg',
  'carlsbad-beach': '35-carlsbad-beach.jpg',
  'carmel-beach': '36-carmel-beach.jpg',
  'casey-key': '37-casey-key.jpg',
  'chatham': '38-chatham.jpg',
  'clearwater': '39-clearwater-beach.jpg',
  'cocoa-beach': '40-cocoa-beach.jpg',
  'coney-island': '41-coney-island.jpg',
  'corolla': '42-corolla.jpg',
  'coronado': '43-coronado-beach.jpg',
  'corpus-christi': '44-corpus-christi-beach.jpg',
  'crane-beach': '45-crane-beach.jpg',
  'crystal-beach-fl': '46-crystal-beach.jpg',
  'dana-point': '47-dana-point.jpg',
  'daytona': '48-daytona-beach.jpg',
  'deerfield-beach': '49-deerfield-beach.jpg',
  'del-mar': '50-del-mar-beach.jpg',
  'dewey-beach': '51-dewey-beach.jpg',
  'dockweiler-beach': '52-dockweiler-beach.jpg',
  'duck': '53-duck.jpg',
  'eastham': '54-eastham.jpg',
  'el-matador': '55-el-matador-beach.jpg',
  'el-segundo': '56-el-segundo-beach.jpg',
  'encinitas': '57-encinitas.jpg',
  'englewood-beach': '58-englewood-beach.jpg',
  'fenwick-island': '59-fenwick-island.jpg',
  'fire-island': '60-fire-island.jpg',
  'flagler-beach': '61-flagler-beach.jpg',
  'florence-beach': '62-florence-beach.jpg',
  'folly-beach': '63-folly-beach.jpg',
  'fort-lauderdale': '64-fort-lauderdale-beach.jpg',
  'fort-myers': '65-fort-myers-beach.jpg',
  'freeport-beach': '66-freeport-beach.jpg',
  'frisco': '67-frisco.jpg',
  'galveston': '68-galveston-beach.jpg',
  'gold-beach': '69-gold-beach.jpg',
  'good-harbor': '70-good-harbor-beach.jpg',
  'grand-isle': '71-grand-isle.jpg',
  'gulf-shores': '72-gulf-shores.jpg',
  'half-moon-bay': '72-half-moon-bay.jpg',
  'hallandale-beach': '74-hallandale-beach.jpg',
  'hampton-beach': '75-hampton-beach.jpg',
  'hanauma-bay': '76-hanauma-bay.jpg',
  'harvey-cedars': '77-harvey-cedars.jpg',
  'hatteras': '78-hatteras.jpg',
  'hermosa-beach': '79-hermosa-beach.jpg',
  'hilton-head': '80-hilton-head.jpg',
  'holgate': '81-holgate.jpg',
  'hollywood-beach': '82-hollywood-beach.jpg',
  'honeymoon-island': '83-honeymoon-island.jpg',
  'huntington': '84-huntington-beach.jpg',
  'imperial-beach': '85-imperial-beach.jpg',
  'indian-rocks': '86-indian-rocks-beech.jpg',
  'indian-shores': '87-indian-shores.jpg',
  'islamorada': '88-islamorada.jpg',
  'jones-beach': '89-jones-beach.jpg',
  'kennebunk': '90-kennebunk-beach.jpg',
  'key-biscayne': '91-key-biscayne.jpg',
  'key-west': '92-key-west-beach.jpg',
  'kiawah-island': '93-kiawah-island.jpg',
  'kill-devil-hills': '94-kill-devil-hills.jpg',
  'kitty-hawk': '95-kitty-hawk.jpg',
  'laguna': '96-laguna-beach.jpg',
  'la-jolla': '97-la-jolla-cove.jpg',
  'lanikai': '98-lanikai-beach.jpg',
  'la-push': '99-la-push-beach.jpg',
  'leo-carrillo': '100-leo-carrillo-beach.jpg',
  'lido-key': '101-lido-key.jpg',
  'lincoln-city': '102-lincoln-city.jpg',
  'long-beach-island': '103-long-beach-island.jpg',
  'long-beach-peninsula': '104-long-beach-peninsula.jpg',
  'longboat-key': '105-longboat-key.jpg',
  'long-branch': '106-long-branch.jpg',
  'loveladies': '107-loveladies.jpg',
  'madeira-beach': '108-madeira-beach.jpg',
  'malibu': '109-malibu-beach.jpg',
  'manasquan': '110-manasquan.jpg',
  'manhattan-beach': '111-manhattan-beach.jpg',
  'manhattan-state-beach': '112-manhattan-state-beach.jpg',
  'manzanita': '113-manzanita-beach.jpg',
  'marathon': '114-marathon.jpg',
  'marco-island': '115-marco-island.jpg',
  'marthas-vineyard': '116-martha-s-vineyard.jpg',
  'matagorda': '117-matagorda-beach.jpg',
  'mendocino': '118-mendocino.jpg',
  'mission-beach': '119-mission-beach.jpg',
  'montauk': '120-montauk.jpg',
  'monterey': '121-monterey-bay.jpg',
  'mustang-island': '122-mustang-island.jpg',
  'myrtle-beach': '123-myrtle-beach.jpg',
  'nags-head': '124-nags-head.jpg',
  'nantucket': '125-nantucket.jpg',
  'naples': '126-naples-beach.jpg',
  'narragansett': '127-narragansett-beach.jpg',
  'new-smyrna': '128-new-smyrna-beach.jpg',
  'newport-beach-ca': '129-newport-beach-ca.jpg',
  'newport-beach-or': '130-newport-beach-or.jpg',
  'newport-beach-ri': '131-newport-beach-ri.jpg',
  'ocean-beach': '132-ocean-beach.jpg',
  'ocean-city-nj': '133-ocean-city.jpg',
  'ocean-city-md': '134-ocean-city-boardwalk.jpg',
  'ocean-shores': '135-ocean-shores.jpg',
  'ogunquit': '136-ogunquit-beach.jpg',
  'old-orchard': '137-old-orchard-beach.jpg',
  'orange-beach': '138-orange-beach.jpg',
  'orleans': '139-orleans.jpg',
  'ormond-beach': '140-ormond-beach.jpg',
  'outer-banks': '141-outer-banks.jpg',
  'pacific-beach': '142-pacific-beach.jpg',
  'pacific-city': '143-pacific-city.jpg',
  'padre-island': '144-padre-island.jpg',
  'panama-city': '145-panama-city-beach.jpg',
  'pass-a-grille': '146-pass-a-grille-beach.jpg',
  'pismo-beach': '147-pismo-beach.jpg',
  'plum-island': '148-plum-island.jpg',
  'point-dume': '149-point-dume.jpg',
  'point-pleasant': '150-point-pleasant.jpg',
  'pompano-beach': '151-pompano-beach.jpg',
  'port-arthur': '152-port-arthur-beach.jpg',
  'port-lavaca': '153-port-lavaca-beach.jpg',
  'provincetown': '154-provincetown.jpg',
  'redington-beach': '155-redington-beach.jpg',
  'redington-shores': '156-redington-shores.jpg',
  'redondo-beach': '157-redondo-beach.jpg',
  'rehoboth': '158-rehoboth-beach.jpg',
  'rialto-beach': '159-rialto-beach.jpg',
  'rockport': '160-rockport-beach.jpg',
  'rodanthe': '161-rodanthe.jpg',
  'rye-beach': '162-rye-beach.jpg',
  'salisbury-beach': '163-salisbury-beach.jpg',
  'salvo': '164-salvo.jpg',
  'san-clemente': '165-san-clemente.jpg',
  'sanibel': '166-sanibel-island.jpg',
  'santa-monica': '167-santa-monica-beach.jpg',
  'sea-isle-city': '168-sea-isle-city.jpg',
  'seaside-beach': '169-seaside-beach.jpg',
  'seaside-heights': '170-seaside-heights.jpg',
  'ship-bottom': '171-ship-bottom.jpg',
  'siesta-key': '172-siesta-key-beach.jpg',
  'solana-beach': '173-solana-beach.jpg',
  'south-beach': '174-south-beach.jpg',
  'southern-shores': '175-southern-shores.jpg',
  'south-padre': '176-south-padre-island.jpg',
  'spring-lake': '177-spring-lake.jpg',
  'st-augustine': '178-st-augustine-beach.jpg',
  'stinson-beach': '179-stinson-beach.jpg',
  'stone-harbor': '180-stone-harbor.jpg',
  'st-pete-beach': '181-st-pete-beach.jpg',
  'sunny-isles': '182-sunny-isles-beach.jpg',
  'surf-city': '183-surf-city.jpg',
  'surfside-beach': '184-surfside-beach.jpg',
  'tarpon-springs': '185-tarpon-springs-beac.jpg',
  'the-hamptons': '186-the-hamptons.jpg',
  'torrey-pines': '187-torrey-pines.jpg',
  'treasure-island': '188-treasure-island.jpg',
  'truro': '189-truro.jpg',
  'tybee-island': '190-tybee-island.jpg',
  'venice-fl': '191-venice-beach-fl.jpg',
  'venice': '192-venice-beach-ca.jpg',
  'virginia-beach': '193-virginia-beach.jpg',
  'waikiki': '194-waikiki-beach.jpg',
  'waves': '195-waves.jpg',
  'wellfleet': '196-wellfleet.jpg',
  'wells-beach': '197-wells-beach.jpg',
  'wildwood': '198-wildwood.jpg',
  'york-beach': '199-york-beach.jpg',
  'zuma-beach': '200-zuma-beach.jpg',
  'miami-beach': '174-south-beach.jpg',
};

const PLACEHOLDER_IMAGES = [
  '1-amelia-island.jpg',
  '2-anna-maria-island.jpg',
  '3-asbury-park.jpg',
  '4-assateague-island.jpg',
  '5-atlantic-city.jpg',
  '7-avon.jpg',
  '8-bal-harbour.jpg',
  '9-bandon-beach.jpg',
];

let placeholderIndex = 0;

function getBeachImageUrl(beachId: string): string {
  if (IMAGE_MAPPING[beachId]) {
    return GITHUB_BASE_URL + IMAGE_MAPPING[beachId];
  }
  const imageName = PLACEHOLDER_IMAGES[placeholderIndex % PLACEHOLDER_IMAGES.length];
  placeholderIndex++;
  return GITHUB_BASE_URL + imageName;
}

/**
 * Live webcam link for each beach, plus whether the camera is a direct view of
 * that exact beach (`'direct'`) or only the closest available cam in the area
 * (`'nearby'`). Beaches with no public live cam are intentionally omitted so no
 * camera button appears for them. Applied to the exported beach lists below.
 */
export const CAMERA_DATA: Record<string, { url: string; type: 'direct' | 'nearby' }> = {
  'miami-beach': { url: 'https://www.skylinewebcams.com/webcam/united-states/florida/miami/south-beach.html', type: 'direct' },
  'santa-monica': { url: 'https://thesurfersview.com/live-cams/california/', type: 'direct' },
  'waikiki': { url: 'https://www.earthcam.com/usa/hawaii/waikiki/', type: 'direct' },
  'myrtle-beach': { url: 'https://www.visitmyrtlebeach.com/web-cams', type: 'direct' },
  'outer-banks': { url: 'https://www.outerbanks.org/webcams/', type: 'direct' },
  'amelia-island': { url: 'https://www.iplivecams.com/live-cams/amelia-island-club-florida-united-states/', type: 'direct' },
  'anna-maria-island': { url: 'https://worldcam.eu/webcams/north-america/florida-usa/36811-bradenton-beach-moose-lodge-anna-maria-island', type: 'direct' },
  'asbury-park': { url: 'https://www.livebeaches.com/webcams/asbury-park-boardwalk/', type: 'direct' },
  'assateague-island': { url: 'https://www.livebeaches.com/state/maryland/', type: 'nearby' },
  'atlantic-city': { url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-jersey/atlantic-city/atlantic-city-boardwalk.html', type: 'direct' },
  'avon-nc': { url: 'https://www.livebeaches.com/webcams/avon-fishing-pier/', type: 'direct' },
  'bal-harbour': { url: 'https://www.mybeachcams.com/florida/miami', type: 'nearby' },
  'bandon-beach': { url: 'https://worldcam.eu/webcams/north-america/oregon-usa/6776-bandon-beach', type: 'direct' },
  'bar-harbor': { url: 'https://www.earthcam.com/usa/maine/barharbor/?cam=barharbor', type: 'direct' },
  'barnegat-light': { url: 'https://www.njbeachcams.com/barnegat-nj-webcam/', type: 'direct' },
  'beach-haven': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'direct' },
  'belleair-beach': { url: 'https://www.beachhunter.net/webcams/', type: 'nearby' },
  'belmar': { url: 'https://playabowls.com/belmar-surf-cam/', type: 'direct' },
  'bethany-beach': { url: 'https://worldcam.eu/webcams/north-america/delaware-usa/27148-south-indian-river-inlet-beach', type: 'direct' },
  'big-pine-key': { url: 'https://www.webcamtaxi.com/en/usa/florida/bahia-honda-state-park.html', type: 'direct' },
  'biloxi-beach': { url: 'https://www.webcamtaxi.com/en/usa/mississippi/biloxi-lighthouse-view.html', type: 'direct' },
  'block-island': { url: 'https://worldcam.eu/webcams/north-america/rhode-island-usa/103-block-island-old-harbor', type: 'direct' },
  'boca-grande': { url: 'https://bocabeacon.com/webcam/', type: 'direct' },
  'bolivar-peninsula': { url: 'https://www.livebeaches.com/webcams/crystal-beach-surf-cam/', type: 'direct' },
  'bonita-springs': { url: 'https://capeweather.com/southwest-florida-live-streaming-webcams/', type: 'nearby' },
  'bradley-beach': { url: 'https://www.livebeaches.com/webcams/bradley-beach-surf-cam/', type: 'direct' },
  'brant-beach': { url: 'https://bbyc.net/', type: 'direct' },
  'brookings-beach': { url: 'https://www.livebeaches.com/webcams/brookings-harbor-oregon-coast-webcam/', type: 'direct' },
  'brownsville-beach': { url: 'https://livebeachcam.net/brownsville-texas-live-webcam/', type: 'direct' },
  'buxton': { url: 'https://www.surfchex.com/cams/hatteras-web-cam/', type: 'direct' },
  'caladesi-island': { url: 'https://www.earthcam.com/usa/florida/dunedin/?cam=dunedin', type: 'direct' },
  'cannon-beach': { url: 'https://www.livebeaches.com/city/cannon-beach-or/', type: 'direct' },
  'cape-cod': { url: 'https://www.livebeaches.com/region/new-england/', type: 'nearby' },
  'cape-hatteras': { url: 'https://www.surfchex.com/cams/hatteras-web-cam/', type: 'direct' },
  'cape-may': { url: 'https://thesurfersview.com/live-cams/new-jersey/cape-may-beach-cam-and-surf-report/', type: 'direct' },
  'capitola-beach': { url: 'https://www.californiabeaches.com/southern-california-beach-webcams/', type: 'nearby' },
  'captiva-island': { url: 'https://sanibel-captiva.org/sanibel-island-webcams/', type: 'direct' },
  'carlsbad-beach': { url: 'https://www.livebeaches.com/state/california/', type: 'direct' },
  'carmel-beach': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'casey-key': { url: 'https://www.beachhunter.net/webcams/', type: 'nearby' },
  'chatham': { url: 'https://www.livebeaches.com/region/new-england/', type: 'nearby' },
  'clearwater': { url: 'https://florida-webcams.com/clearwater-beach-webcam/', type: 'direct' },
  'cocoa-beach': { url: 'https://www.youtube.com/watch?v=JsEvqW8ymy0', type: 'direct' },
  'coney-island': { url: 'https://www.livebeaches.com/webcams/luna-park-coney-island-webcam/', type: 'direct' },
  'corolla': { url: 'https://www.visitob.com/webcams/corolla-nc-beach-cam/', type: 'direct' },
  'coronado': { url: 'https://www.sandiego.org/article/live-web-cams-sending-san-diego-warmth', type: 'direct' },
  'corpus-christi': { url: 'https://texasbeaches.net/live-beach-cams/', type: 'direct' },
  'crane-beach': { url: 'https://www.livebeaches.com/region/new-england/', type: 'nearby' },
  'crystal-beach-fl': { url: 'https://www.beachhunter.net/webcams/', type: 'nearby' },
  'dana-point': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'daytona': { url: 'https://www.livebeaches.com/city/daytona-beach-fl/', type: 'direct' },
  'deerfield-beach': { url: 'https://www.eastcoastcams.com/florida/', type: 'direct' },
  'del-mar': { url: 'https://www.mybeachcams.com/california/san-diego', type: 'direct' },
  'dewey-beach': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'direct' },
  'dockweiler-beach': { url: 'https://www.californiabeaches.com/southern-california-beach-webcams/', type: 'nearby' },
  'duck': { url: 'https://www.obxconnection.com/outer-banks-webcams/All-OBX-Webcams.aspx', type: 'direct' },
  'eastham': { url: 'https://www.livebeaches.com/region/new-england/', type: 'nearby' },
  'el-matador': { url: 'https://thesurfersview.com/live-cams/california/', type: 'nearby' },
  'el-segundo': { url: 'https://www.californiabeaches.com/southern-california-beach-webcams/', type: 'nearby' },
  'encinitas': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'englewood-beach': { url: 'https://www.pureflorida.com/beaches/live-beach-cam/', type: 'direct' },
  'fenwick-island': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'nearby' },
  'fire-island': { url: 'https://www.livebeaches.com/city/fire-island-ny/', type: 'direct' },
  'flagler-beach': { url: 'https://www.eastcoastcams.com/florida/', type: 'direct' },
  'florence-beach': { url: 'https://coastoregon.com/webcams/', type: 'direct' },
  'folly-beach': { url: 'https://thesurfersview.com/live-cams/florida/cocoa-beach-surf-cam/', type: 'direct' },
  'fort-lauderdale': { url: 'https://www.discoverlbts.com/live-beach-webcam/', type: 'direct' },
  'fort-myers': { url: 'https://sanibel-captiva.org/sanibel-island-webcams/', type: 'direct' },
  'freeport-beach': { url: 'https://texasbeaches.net/live-beach-cams/', type: 'nearby' },
  'frisco': { url: 'https://www.surfchex.com/cams/hatteras-web-cam/', type: 'nearby' },
  'galveston': { url: 'https://www.livebeaches.com/city/galveston-tx/', type: 'direct' },
  'gold-beach': { url: 'https://coastoregon.com/webcams/', type: 'direct' },
  'good-harbor': { url: 'https://www.livebeaches.com/region/new-england/', type: 'nearby' },
  'gulf-shores': { url: 'https://www.brett-robinson.com/webcams', type: 'direct' },
  'half-moon-bay': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'hallandale-beach': { url: 'https://www.mybeachcams.com/florida/miami', type: 'nearby' },
  'hampton-beach': { url: 'https://www.livebeaches.com/city/hampton-beach-nh/', type: 'direct' },
  'hanauma-bay': { url: 'https://www.mybeachcams.com/hawaii/oahu', type: 'nearby' },
  'harvey-cedars': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'direct' },
  'hatteras': { url: 'https://www.surfchex.com/cams/hatteras-web-cam/', type: 'direct' },
  'hermosa-beach': { url: 'https://thesurfersview.com/live-cams/california/', type: 'direct' },
  'hilton-head': { url: 'https://www.palmettodunes.com/news-and-media/webcams', type: 'direct' },
  'holgate': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'nearby' },
  'hollywood-beach': { url: 'https://www.eastcoastcams.com/florida/', type: 'direct' },
  'honeymoon-island': { url: 'https://www.earthcam.com/usa/florida/dunedin/?cam=dunedin', type: 'direct' },
  'huntington': { url: 'https://hbcams.com/', type: 'direct' },
  'imperial-beach': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'indian-rocks': { url: 'https://www.eastcoastcams.com/florida/', type: 'direct' },
  'indian-shores': { url: 'https://www.eastcoastcams.com/florida/', type: 'direct' },
  'islamorada': { url: 'https://florida-webcams.com/', type: 'direct' },
  'jones-beach': { url: 'https://www.livebeaches.com/city/long-island-ny/', type: 'direct' },
  'kennebunk': { url: 'https://maine-webcams.com/kennebunk-beach-webcam/', type: 'direct' },
  'key-biscayne': { url: 'https://www.eastcoastcams.com/florida/', type: 'direct' },
  'key-west': { url: 'https://www.livebeaches.com/state/florida/', type: 'direct' },
  'kiawah-island': { url: 'https://www.eastcoastcams.com/south-carolina/hilton-head-island/', type: 'nearby' },
  'kill-devil-hills': { url: 'https://www.outerbanksblue.com/outer-banks-beach-cam', type: 'direct' },
  'kitty-hawk': { url: 'https://www.livebeaches.com/city/kitty-hawk-nc/', type: 'direct' },
  'laguna': { url: 'https://www.livebeaches.com/state/california/', type: 'direct' },
  'la-jolla': { url: 'https://www.ljshoreshotel.com/beach-cam/', type: 'direct' },
  'lanikai': { url: 'https://www.mybeachcams.com/hawaii/oahu', type: 'nearby' },
  'leo-carrillo': { url: 'https://thesurfersview.com/live-cams/california/', type: 'nearby' },
  'lido-key': { url: 'https://www.livebeaches.com/city/siesta-key-beach-fl/', type: 'nearby' },
  'lincoln-city': { url: 'https://www.livebeaches.com/state/oregon/', type: 'direct' },
  'long-beach-island': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'direct' },
  'longboat-key': { url: 'https://www.eastcoastcams.com/florida/', type: 'direct' },
  'long-branch': { url: 'https://www.njbeachcams.com/', type: 'direct' },
  'loveladies': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'nearby' },
  'madeira-beach': { url: 'https://www.mybeachcams.com/florida/gulf-coast', type: 'direct' },
  'malibu': { url: 'https://thesurfersview.com/live-cams/california/', type: 'direct' },
  'manasquan': { url: 'https://www.njbeachcams.com/', type: 'direct' },
  'manhattan-beach': { url: 'https://www.californiabeaches.com/southern-california-beach-webcams/', type: 'nearby' },
  'manhattan-state-beach': { url: 'https://www.californiabeaches.com/southern-california-beach-webcams/', type: 'nearby' },
  'manzanita': { url: 'https://coastoregon.com/webcams/', type: 'direct' },
  'marathon': { url: 'https://florida-webcams.com/', type: 'direct' },
  'marco-island': { url: 'https://www.livebeaches.com/city/fort-myers-fl/', type: 'nearby' },
  'marthas-vineyard': { url: 'https://www.livebeaches.com/region/new-england/', type: 'direct' },
  'matagorda': { url: 'https://texasbeaches.net/live-beach-cams/', type: 'nearby' },
  'mendocino': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'mission-beach': { url: 'https://hdontap.com/stream/475932/mission-beach-and-crystal-pier-live-cam/', type: 'direct' },
  'montauk': { url: 'https://www.livebeaches.com/city/montauk-ny/', type: 'direct' },
  'monterey': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'mustang-island': { url: 'https://www.portaransas.org/plan/webcam/', type: 'direct' },
  'nags-head': { url: 'https://www.surfchex.com/cams/nags-head-web-cam/', type: 'direct' },
  'nantucket': { url: 'https://www.livebeaches.com/region/new-england/', type: 'direct' },
  'naples': { url: 'https://www.mybeachcams.com/florida', type: 'direct' },
  'narragansett': { url: 'https://www.livebeaches.com/region/new-england/', type: 'direct' },
  'new-smyrna': { url: 'https://www.livebeaches.com/city/new-smyrna-beach-fl/', type: 'direct' },
  'newport-beach-ca': { url: 'https://www.livebeaches.com/state/california/', type: 'direct' },
  'newport-beach-or': { url: 'https://www.skylinewebcams.com/en/webcam/united-states/oregon/newport/yaquina-bay-newport-oregon-coast.html', type: 'direct' },
  'newport-beach-ri': { url: 'https://www.livebeaches.com/region/new-england/', type: 'direct' },
  'ocean-beach': { url: 'https://thesurfersview.com/live-cams/california/', type: 'direct' },
  'ocean-city-nj': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'direct' },
  'ocean-city-md': { url: 'https://www.livebeaches.com/state/maryland/', type: 'direct' },
  'ogunquit': { url: 'https://maine-webcams.com/ogunquit-beach-webcam/', type: 'direct' },
  'old-orchard': { url: 'https://maine-webcams.com/old-orchard-beach-webcam/', type: 'direct' },
  'orange-beach': { url: 'https://www.brett-robinson.com/webcams', type: 'direct' },
  'orleans': { url: 'https://www.livebeaches.com/region/new-england/', type: 'nearby' },
  'ormond-beach': { url: 'https://www.mybeachcams.com/florida', type: 'direct' },
  'pacific-beach': { url: 'https://www.catamaranresort.com/live-cam', type: 'direct' },
  'pacific-city': { url: 'https://www.livebeaches.com/state/oregon/', type: 'direct' },
  'padre-island': { url: 'https://texasbeaches.net/live-beach-cams/', type: 'direct' },
  'panama-city': { url: 'https://www.livebeaches.com/city/panama-city-beach-fl/', type: 'direct' },
  'pass-a-grille': { url: 'https://www.livebeaches.com/city/st-pete-beach-fl/', type: 'nearby' },
  'pismo-beach': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'plum-island': { url: 'https://www.livebeaches.com/region/new-england/', type: 'nearby' },
  'point-dume': { url: 'https://thesurfersview.com/live-cams/california/', type: 'nearby' },
  'point-pleasant': { url: 'https://www.njbeachcams.com/central-new-jersey/point-pleasant-beach-webcam/', type: 'direct' },
  'pompano-beach': { url: 'https://www.mybeachcams.com/florida', type: 'direct' },
  'port-arthur': { url: 'https://texasbeaches.net/live-beach-cams/', type: 'nearby' },
  'port-lavaca': { url: 'https://texasbeaches.net/live-beach-cams/', type: 'nearby' },
  'provincetown': { url: 'https://www.livebeaches.com/region/new-england/', type: 'direct' },
  'redington-beach': { url: 'https://www.beachhunter.net/webcams/', type: 'nearby' },
  'redington-shores': { url: 'https://www.beachhunter.net/webcams/', type: 'nearby' },
  'redondo-beach': { url: 'https://www.californiabeaches.com/southern-california-beach-webcams/', type: 'nearby' },
  'rehoboth': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'direct' },
  'rockport': { url: 'https://www.mybeachcams.com/texas', type: 'direct' },
  'rodanthe': { url: 'https://www.obxconnection.com/outer-banks-webcams/All-OBX-Webcams.aspx', type: 'direct' },
  'rye-beach': { url: 'https://www.livebeaches.com/city/north-hampton-nh/', type: 'direct' },
  'salisbury-beach': { url: 'https://www.livebeaches.com/region/new-england/', type: 'direct' },
  'salvo': { url: 'https://www.surfchex.com/', type: 'nearby' },
  'san-clemente': { url: 'https://www.livebeaches.com/city/san-clemente-ca/', type: 'direct' },
  'sanibel': { url: 'https://sanibel-captiva.org/sanibel-island-webcams/', type: 'direct' },
  'sea-isle-city': { url: 'https://www.livebeaches.com/state/new-jersey/', type: 'direct' },
  'seaside-beach': { url: 'https://www.skylinewebcams.com/en/webcam/united-states/oregon/seaside/beach.html', type: 'direct' },
  'seaside-heights': { url: 'https://njbeachcams.com/central-new-jersey/seaside-heights-boardwalk-cam/', type: 'direct' },
  'ship-bottom': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'direct' },
  'siesta-key': { url: 'https://www.livebeaches.com/city/siesta-key-beach-fl/', type: 'direct' },
  'solana-beach': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'south-beach': { url: 'https://www.skylinewebcams.com/webcam/united-states/florida/miami/south-beach.html', type: 'direct' },
  'southern-shores': { url: 'https://www.twiddy.com/outer-banks/webcam/', type: 'direct' },
  'south-padre': { url: 'https://texasbeaches.net/live-beach-cams/', type: 'direct' },
  'spring-lake': { url: 'https://www.njbeachcams.com/', type: 'direct' },
  'st-augustine': { url: 'https://www.eastcoastcams.com/florida/', type: 'direct' },
  'stinson-beach': { url: 'https://www.livebeaches.com/state/california/', type: 'nearby' },
  'stone-harbor': { url: 'https://attheshore.com/', type: 'direct' },
  'st-pete-beach': { url: 'https://www.mybeachcams.com/florida/gulf-coast', type: 'direct' },
  'sunny-isles': { url: 'https://www.mybeachcams.com/florida/miami', type: 'direct' },
  'surf-city': { url: 'https://thesurfersview.com/live-cams/new-jersey/', type: 'direct' },
  'surfside-beach': { url: 'https://texasbeaches.net/live-beach-cams/', type: 'nearby' },
  'tarpon-springs': { url: 'https://www.beachhunter.net/webcams/', type: 'nearby' },
  'the-hamptons': { url: 'https://www.livebeaches.com/state/new-york/', type: 'direct' },
  'torrey-pines': { url: 'https://www.mybeachcams.com/california/san-diego', type: 'direct' },
  'treasure-island': { url: 'https://www.beachhunter.net/webcams/', type: 'direct' },
  'truro': { url: 'https://www.livebeaches.com/region/new-england/', type: 'nearby' },
  'tybee-island': { url: 'https://www.socoastal.com/best-live-tybee-island-webcams/', type: 'direct' },
  'venice-fl': { url: 'https://www.eastcoastcams.com/florida/', type: 'direct' },
  'venice': { url: 'https://www.earthcam.com/usa/california/venicebeach/index.php', type: 'direct' },
  'virginia-beach': { url: 'https://www.surfchex.com/cams/virginia-beach-web-cam/', type: 'direct' },
  'waves': { url: 'https://www.surfchex.com/', type: 'direct' },
  'wellfleet': { url: 'https://www.livebeaches.com/region/new-england/', type: 'direct' },
  'wells-beach': { url: 'https://maine-webcams.com/wells-beach-webcam/', type: 'direct' },
  'wildwood': { url: 'https://www.fox29.com/wildwood-webcam', type: 'direct' },
  'york-beach': { url: 'https://maine-webcams.com/york-beach-webcam/', type: 'direct' },
  'zuma-beach': { url: 'https://thesurfersview.com/live-cams/california/', type: 'nearby' },
};

const POPULAR_BEACHES_BASE: Beach[] = [
  {
    id: 'miami-beach',
    name: 'Miami Beach',
    state: 'Florida',
    latitude: 25.7907,
    longitude: -80.1300,
    stationId: '8723214',
    waterTempStationId: '8723214',
    imageUrl: getBeachImageUrl('miami-beach'),
  },
  {
    id: 'santa-monica',
    name: 'Santa Monica Beach',
    state: 'California',
    latitude: 34.0195,
    longitude: -118.4912,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('santa-monica'),
  },
  {
    id: 'waikiki',
    name: 'Waikiki Beach',
    state: 'Hawaii',
    latitude: 21.2793,
    longitude: -157.8293,
    stationId: '1612340',
    waterTempStationId: '1612340',
    imageUrl: getBeachImageUrl('waikiki'),
  },
  {
    id: 'myrtle-beach',
    name: 'Myrtle Beach',
    state: 'South Carolina',
    latitude: 33.6891,
    longitude: -78.8867,
    stationId: '8661070',
    waterTempStationId: '8661070',
    imageUrl: getBeachImageUrl('myrtle-beach'),
  },
  {
    id: 'outer-banks',
    name: 'Outer Banks',
    state: 'North Carolina',
    latitude: 35.5585,
    longitude: -75.4665,
    stationId: '8652587',
    waterTempStationId: '8652587',
    imageUrl: getBeachImageUrl('outer-banks'),
  },
];

const ALL_BEACHES_BASE: Beach[] = [
  ...POPULAR_BEACHES_BASE,
  {
    id: 'amelia-island',
    name: 'Amelia Island',
    state: 'Florida',
    latitude: 30.6719,
    longitude: -81.4606,
    stationId: '8720030',
    waterTempStationId: '8720218',
    imageUrl: getBeachImageUrl('amelia-island'),
  },
  {
    id: 'anna-maria-island',
    name: 'Anna Maria Island',
    state: 'Florida',
    latitude: 27.5314,
    longitude: -82.7326,
    stationId: '8726520',
    waterTempStationId: '8726384',
    imageUrl: getBeachImageUrl('anna-maria-island'),
  },
  {
    id: 'asbury-park',
    name: 'Asbury Park',
    state: 'New Jersey',
    latitude: 40.2204,
    longitude: -74.0121,
    stationId: '8531680',
    waterTempStationId: '8531680',
    imageUrl: getBeachImageUrl('asbury-park'),
  },
  {
    id: 'assateague-island',
    name: 'Assateague Island',
    state: 'Maryland',
    latitude: 38.2211,
    longitude: -75.1544,
    stationId: '8570283',
    waterTempStationId: '8570283',
    imageUrl: getBeachImageUrl('assateague-island'),
  },
  {
    id: 'atlantic-city',
    name: 'Atlantic City',
    state: 'New Jersey',
    latitude: 39.3643,
    longitude: -74.4229,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('atlantic-city'),
  },
  {
    id: 'avalon-beach',
    name: 'Avalon Beach',
    state: 'New Jersey',
    latitude: 39.1007,
    longitude: -74.7196,
    stationId: '8536110',
    waterTempStationId: '8536110',
    imageUrl: getBeachImageUrl('avalon-beach'),
  },
  {
    id: 'avon-nc',
    name: 'Avon',
    state: 'North Carolina',
    latitude: 35.3532,
    longitude: -75.5063,
    stationId: '8654467',
    waterTempStationId: '8654467',
    imageUrl: getBeachImageUrl('avon-nc'),
  },
  {
    id: 'bal-harbour',
    name: 'Bal Harbour',
    state: 'Florida',
    latitude: 25.8923,
    longitude: -80.1234,
    stationId: '8723214',
    waterTempStationId: '8723214',
    imageUrl: getBeachImageUrl('bal-harbour'),
  },
  {
    id: 'bandon-beach',
    name: 'Bandon Beach',
    state: 'Oregon',
    latitude: 43.1190,
    longitude: -124.4084,
    stationId: '9431647',
    waterTempStationId: '9431647',
    imageUrl: getBeachImageUrl('bandon-beach'),
  },
  {
    id: 'bar-harbor',
    name: 'Bar Harbor',
    state: 'Maine',
    latitude: 44.3876,
    longitude: -68.2039,
    stationId: '8413320',
    waterTempStationId: '8413320',
    imageUrl: getBeachImageUrl('bar-harbor'),
  },
  {
    id: 'barnegat-light',
    name: 'Barnegat Light',
    state: 'New Jersey',
    latitude: 39.7543,
    longitude: -74.1060,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('barnegat-light'),
  },
  {
    id: 'beach-haven',
    name: 'Beach Haven',
    state: 'New Jersey',
    latitude: 39.5593,
    longitude: -74.2432,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('beach-haven'),
  },
  {
    id: 'belleair-beach',
    name: 'Belleair Beach',
    state: 'Florida',
    latitude: 27.9192,
    longitude: -82.8376,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('belleair-beach'),
  },
  {
    id: 'belmar',
    name: 'Belmar',
    state: 'New Jersey',
    latitude: 40.1785,
    longitude: -74.0218,
    stationId: '8531680',
    waterTempStationId: '8531680',
    imageUrl: getBeachImageUrl('belmar'),
  },
  {
    id: 'bethany-beach',
    name: 'Bethany Beach',
    state: 'Delaware',
    latitude: 38.5393,
    longitude: -75.0552,
    stationId: '8557380',
    waterTempStationId: '8570283',
    imageUrl: getBeachImageUrl('bethany-beach'),
  },
  {
    id: 'big-pine-key',
    name: 'Big Pine Key',
    state: 'Florida',
    latitude: 24.6714,
    longitude: -81.3534,
    stationId: '8724580',
    waterTempStationId: '8723970',
    imageUrl: getBeachImageUrl('big-pine-key'),
  },
  {
    id: 'biloxi-beach',
    name: 'Biloxi Beach',
    state: 'Mississippi',
    latitude: 30.3960,
    longitude: -88.8853,
    stationId: '8747437',
    waterTempStationId: '8741533',
    imageUrl: getBeachImageUrl('biloxi-beach'),
  },
  {
    id: 'block-island',
    name: 'Block Island',
    state: 'Rhode Island',
    latitude: 41.1681,
    longitude: -71.5800,
    stationId: '8452660',
    waterTempStationId: '8510560',
    imageUrl: getBeachImageUrl('block-island'),
  },
  {
    id: 'boca-grande',
    name: 'Boca Grande',
    state: 'Florida',
    latitude: 26.7273,
    longitude: -82.2626,
    stationId: '8725110',
    waterTempStationId: '8725520',
    imageUrl: getBeachImageUrl('boca-grande'),
  },
  {
    id: 'bolivar-peninsula',
    name: 'Bolivar Peninsula',
    state: 'Texas',
    latitude: 29.4558,
    longitude: -94.6827,
    stationId: '8771450',
    waterTempStationId: '8771341',
    imageUrl: getBeachImageUrl('bolivar-peninsula'),
  },
  {
    id: 'bonita-springs',
    name: 'Bonita Springs',
    state: 'Florida',
    latitude: 26.3398,
    longitude: -81.8773,
    stationId: '8725110',
    waterTempStationId: '8725520',
    imageUrl: getBeachImageUrl('bonita-springs'),
  },
  {
    id: 'bradley-beach',
    name: 'Bradley Beach',
    state: 'New Jersey',
    latitude: 40.2026,
    longitude: -74.0121,
    stationId: '8531680',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('bradley-beach'),
  },
  {
    id: 'brant-beach',
    name: 'Brant Beach',
    state: 'New Jersey',
    latitude: 39.6451,
    longitude: -74.1932,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('brant-beach'),
  },
  {
    id: 'brookings-beach',
    name: 'Brookings Beach',
    state: 'Oregon',
    latitude: 42.0526,
    longitude: -124.2840,
    stationId: '9431647',
    waterTempStationId: '9419750',
    imageUrl: getBeachImageUrl('brookings-beach'),
  },
  {
    id: 'brownsville-beach',
    name: 'Brownsville Beach',
    state: 'Texas',
    latitude: 25.9017,
    longitude: -97.4975,
    stationId: '8779770',
    waterTempStationId: '8779770',
    imageUrl: getBeachImageUrl('brownsville-beach'),
  },
  {
    id: 'buxton',
    name: 'Buxton',
    state: 'North Carolina',
    latitude: 35.2693,
    longitude: -75.5352,
    stationId: '8654467',
    waterTempStationId: '8654467',
    imageUrl: getBeachImageUrl('buxton'),
  },
  {
    id: 'caladesi-island',
    name: 'Caladesi Island',
    state: 'Florida',
    latitude: 28.0253,
    longitude: -82.8176,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('caladesi-island'),
  },
  {
    id: 'cannon-beach',
    name: 'Cannon Beach',
    state: 'Oregon',
    latitude: 45.8918,
    longitude: -123.9615,
    stationId: '9435380',
    waterTempStationId: '9440422',
    imageUrl: getBeachImageUrl('cannon-beach'),
  },
  {
    id: 'cape-cod',
    name: 'Cape Cod National Seashore',
    state: 'Massachusetts',
    latitude: 41.9270,
    longitude: -70.0461,
    stationId: '8447930',
    waterTempStationId: '8447930',
    imageUrl: getBeachImageUrl('cape-cod'),
  },
  {
    id: 'cape-hatteras',
    name: 'Cape Hatteras',
    state: 'North Carolina',
    latitude: 35.2226,
    longitude: -75.5291,
    stationId: '8654467',
    waterTempStationId: '8654467',
    imageUrl: getBeachImageUrl('cape-hatteras'),
  },
  {
    id: 'cape-may',
    name: 'Cape May',
    state: 'New Jersey',
    latitude: 38.9351,
    longitude: -74.9060,
    stationId: '8536110',
    waterTempStationId: '8536110',
    imageUrl: getBeachImageUrl('cape-may'),
  },
  {
    id: 'capitola-beach',
    name: 'Capitola Beach',
    state: 'California',
    latitude: 36.9741,
    longitude: -121.9535,
    stationId: '9413450',
    waterTempStationId: '9413450',
    imageUrl: getBeachImageUrl('capitola-beach'),
  },
  {
    id: 'captiva-island',
    name: 'Captiva Island',
    state: 'Florida',
    latitude: 26.5312,
    longitude: -82.1926,
    stationId: '8725110',
    waterTempStationId: '8725520',
    imageUrl: getBeachImageUrl('captiva-island'),
  },
  {
    id: 'carlsbad-beach',
    name: 'Carlsbad Beach',
    state: 'California',
    latitude: 33.1581,
    longitude: -117.3506,
    stationId: '9410170',
    waterTempStationId: '9410230',
    imageUrl: getBeachImageUrl('carlsbad-beach'),
  },
  {
    id: 'carmel-beach',
    name: 'Carmel Beach',
    state: 'California',
    latitude: 36.5553,
    longitude: -121.9233,
    stationId: '9413450',
    waterTempStationId: '9413450',
    imageUrl: getBeachImageUrl('carmel-beach'),
  },
  {
    id: 'casey-key',
    name: 'Casey Key',
    state: 'Florida',
    latitude: 27.1253,
    longitude: -82.5376,
    stationId: '8726520',
    waterTempStationId: '8726384',
    imageUrl: getBeachImageUrl('casey-key'),
  },
  {
    id: 'chatham',
    name: 'Chatham',
    state: 'Massachusetts',
    latitude: 41.6821,
    longitude: -69.9597,
    stationId: '8447930',
    waterTempStationId: '8449130',
    imageUrl: getBeachImageUrl('chatham'),
  },
  {
    id: 'clearwater',
    name: 'Clearwater Beach',
    state: 'Florida',
    latitude: 27.9659,
    longitude: -82.8001,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('clearwater'),
  },
  {
    id: 'cocoa-beach',
    name: 'Cocoa Beach',
    state: 'Florida',
    latitude: 28.3200,
    longitude: -80.6076,
    stationId: '8721164',
    waterTempStationId: '8721604',
    imageUrl: getBeachImageUrl('cocoa-beach'),
  },
  {
    id: 'coney-island',
    name: 'Coney Island',
    state: 'New York',
    latitude: 40.5755,
    longitude: -73.9707,
    stationId: '8518750',
    waterTempStationId: '8531680',
    imageUrl: getBeachImageUrl('coney-island'),
  },
  {
    id: 'corolla',
    name: 'Corolla',
    state: 'North Carolina',
    latitude: 36.3760,
    longitude: -75.8269,
    stationId: '8651370',
    waterTempStationId: '8651370',
    imageUrl: getBeachImageUrl('corolla'),
  },
  {
    id: 'coronado',
    name: 'Coronado Beach',
    state: 'California',
    latitude: 32.6859,
    longitude: -117.1831,
    stationId: '9410170',
    waterTempStationId: '9410170',
    imageUrl: getBeachImageUrl('coronado'),
  },
  {
    id: 'corpus-christi',
    name: 'Corpus Christi Beach',
    state: 'Texas',
    latitude: 27.8006,
    longitude: -97.3964,
    stationId: '8775870',
    waterTempStationId: '8775296',
    imageUrl: getBeachImageUrl('corpus-christi'),
  },
  {
    id: 'crane-beach',
    name: 'Crane Beach',
    state: 'Massachusetts',
    latitude: 42.6834,
    longitude: -70.7698,
    stationId: '8443970',
    waterTempStationId: '8419870',
    imageUrl: getBeachImageUrl('crane-beach'),
  },
  {
    id: 'crystal-beach-fl',
    name: 'Crystal Beach',
    state: 'Florida',
    latitude: 28.0856,
    longitude: -82.7859,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('crystal-beach-fl'),
  },
  {
    id: 'dana-point',
    name: 'Dana Point',
    state: 'California',
    latitude: 33.4673,
    longitude: -117.6981,
    stationId: '9410660',
    waterTempStationId: '9410230',
    imageUrl: getBeachImageUrl('dana-point'),
  },
  {
    id: 'daytona',
    name: 'Daytona Beach',
    state: 'Florida',
    latitude: 29.2108,
    longitude: -81.0228,
    stationId: '8721164',
    waterTempStationId: '8721604',
    imageUrl: getBeachImageUrl('daytona'),
  },
  {
    id: 'deerfield-beach',
    name: 'Deerfield Beach',
    state: 'Florida',
    latitude: 26.3184,
    longitude: -80.0998,
    stationId: '8722670',
    waterTempStationId: '8722956',
    imageUrl: getBeachImageUrl('deerfield-beach'),
  },
  {
    id: 'del-mar',
    name: 'Del Mar Beach',
    state: 'California',
    latitude: 32.9595,
    longitude: -117.2653,
    stationId: '9410170',
    waterTempStationId: '9410230',
    imageUrl: getBeachImageUrl('del-mar'),
  },
  {
    id: 'dewey-beach',
    name: 'Dewey Beach',
    state: 'Delaware',
    latitude: 38.6929,
    longitude: -75.0732,
    stationId: '8557380',
    waterTempStationId: '8557380',
    imageUrl: getBeachImageUrl('dewey-beach'),
  },
  {
    id: 'dockweiler-beach',
    name: 'Dockweiler Beach',
    state: 'California',
    latitude: 33.9192,
    longitude: -118.4365,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('dockweiler-beach'),
  },
  {
    id: 'duck',
    name: 'Duck',
    state: 'North Carolina',
    latitude: 36.1593,
    longitude: -75.7460,
    stationId: '8651370',
    waterTempStationId: '8651370',
    imageUrl: getBeachImageUrl('duck'),
  },
  {
    id: 'eastham',
    name: 'Eastham',
    state: 'Massachusetts',
    latitude: 41.8301,
    longitude: -69.9745,
    stationId: '8447930',
    waterTempStationId: '8449130',
    imageUrl: getBeachImageUrl('eastham'),
  },
  {
    id: 'el-matador',
    name: 'El Matador Beach',
    state: 'California',
    latitude: 34.0359,
    longitude: -118.8781,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('el-matador'),
  },
  {
    id: 'el-segundo',
    name: 'El Segundo Beach',
    state: 'California',
    latitude: 33.9192,
    longitude: -118.4165,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('el-segundo'),
  },
  {
    id: 'encinitas',
    name: 'Encinitas',
    state: 'California',
    latitude: 33.0370,
    longitude: -117.2920,
    stationId: '9410170',
    waterTempStationId: '9410230',
    imageUrl: getBeachImageUrl('encinitas'),
  },
  {
    id: 'englewood-beach',
    name: 'Englewood Beach',
    state: 'Florida',
    latitude: 26.9620,
    longitude: -82.3526,
    stationId: '8725110',
    waterTempStationId: '8725520',
    imageUrl: getBeachImageUrl('englewood-beach'),
  },
  {
    id: 'fenwick-island',
    name: 'Fenwick Island',
    state: 'Delaware',
    latitude: 38.4501,
    longitude: -75.0532,
    stationId: '8557380',
    waterTempStationId: '8570283',
    imageUrl: getBeachImageUrl('fenwick-island'),
  },
  {
    id: 'fire-island',
    name: 'Fire Island',
    state: 'New York',
    latitude: 40.6451,
    longitude: -73.1540,
    stationId: '8510560',
    waterTempStationId: '8516945',
    imageUrl: getBeachImageUrl('fire-island'),
  },
  {
    id: 'flagler-beach',
    name: 'Flagler Beach',
    state: 'Florida',
    latitude: 29.4730,
    longitude: -81.1287,
    stationId: '8721164',
    waterTempStationId: '8720218',
    imageUrl: getBeachImageUrl('flagler-beach'),
  },
  {
    id: 'florence-beach',
    name: 'Florence Beach',
    state: 'Oregon',
    latitude: 43.9829,
    longitude: -124.1012,
    stationId: '9435380',
    waterTempStationId: '9435380',
    imageUrl: getBeachImageUrl('florence-beach'),
  },
  {
    id: 'folly-beach',
    name: 'Folly Beach',
    state: 'South Carolina',
    latitude: 32.6552,
    longitude: -79.9403,
    stationId: '8665530',
    waterTempStationId: '8665530',
    imageUrl: getBeachImageUrl('folly-beach'),
  },
  {
    id: 'fort-lauderdale',
    name: 'Fort Lauderdale Beach',
    state: 'Florida',
    latitude: 26.1224,
    longitude: -80.1373,
    stationId: '8722670',
    waterTempStationId: '8722956',
    imageUrl: getBeachImageUrl('fort-lauderdale'),
  },
  {
    id: 'fort-myers',
    name: 'Fort Myers Beach',
    state: 'Florida',
    latitude: 26.4518,
    longitude: -81.9481,
    stationId: '8725110',
    waterTempStationId: '8725520',
    imageUrl: getBeachImageUrl('fort-myers'),
  },
  {
    id: 'freeport-beach',
    name: 'Freeport Beach',
    state: 'Texas',
    latitude: 28.9533,
    longitude: -95.3099,
    stationId: '8772447',
    waterTempStationId: '8772471',
    imageUrl: getBeachImageUrl('freeport-beach'),
  },
  {
    id: 'frisco',
    name: 'Frisco',
    state: 'North Carolina',
    latitude: 35.2382,
    longitude: -75.6235,
    stationId: '8654467',
    waterTempStationId: '8654467',
    imageUrl: getBeachImageUrl('frisco'),
  },
  {
    id: 'galveston',
    name: 'Galveston Beach',
    state: 'Texas',
    latitude: 29.3013,
    longitude: -94.7977,
    stationId: '8771450',
    waterTempStationId: '8771450',
    imageUrl: getBeachImageUrl('galveston'),
  },
  {
    id: 'gold-beach',
    name: 'Gold Beach',
    state: 'Oregon',
    latitude: 42.4071,
    longitude: -124.4218,
    stationId: '9431647',
    waterTempStationId: '9431647',
    imageUrl: getBeachImageUrl('gold-beach'),
  },
  {
    id: 'good-harbor',
    name: 'Good Harbor Beach',
    state: 'Massachusetts',
    latitude: 42.6234,
    longitude: -70.6698,
    stationId: '8443970',
    waterTempStationId: '8419870',
    imageUrl: getBeachImageUrl('good-harbor'),
  },
  {
    id: 'grand-isle',
    name: 'Grand Isle',
    state: 'Louisiana',
    latitude: 29.2633,
    longitude: -89.9570,
    stationId: '8761724',
    waterTempStationId: '8761724',
    imageUrl: getBeachImageUrl('grand-isle'),
  },
  {
    id: 'gulf-shores',
    name: 'Gulf Shores',
    state: 'Alabama',
    latitude: 30.2460,
    longitude: -87.7008,
    stationId: '8735180',
    waterTempStationId: '8735180',
    imageUrl: getBeachImageUrl('gulf-shores'),
  },
  {
    id: 'half-moon-bay',
    name: 'Half Moon Bay',
    state: 'California',
    latitude: 37.4636,
    longitude: -122.4286,
    stationId: '9414290',
    waterTempStationId: '9414750',
    imageUrl: getBeachImageUrl('half-moon-bay'),
  },
  {
    id: 'hallandale-beach',
    name: 'Hallandale Beach',
    state: 'Florida',
    latitude: 25.9812,
    longitude: -80.1484,
    stationId: '8723214',
    waterTempStationId: '8722956',
    imageUrl: getBeachImageUrl('hallandale-beach'),
  },
  {
    id: 'hampton-beach',
    name: 'Hampton Beach',
    state: 'New Hampshire',
    latitude: 42.9001,
    longitude: -70.8109,
    stationId: '8423898',
    waterTempStationId: '8419870',
    imageUrl: getBeachImageUrl('hampton-beach'),
  },
  {
    id: 'hanauma-bay',
    name: 'Hanauma Bay',
    state: 'Hawaii',
    latitude: 21.2693,
    longitude: -157.6943,
    stationId: '1612340',
    waterTempStationId: '1612340',
    imageUrl: getBeachImageUrl('hanauma-bay'),
  },
  {
    id: 'harvey-cedars',
    name: 'Harvey Cedars',
    state: 'New Jersey',
    latitude: 39.6951,
    longitude: -74.1360,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('harvey-cedars'),
  },
  {
    id: 'hatteras',
    name: 'Hatteras',
    state: 'North Carolina',
    latitude: 35.2118,
    longitude: -75.6974,
    stationId: '8654467',
    waterTempStationId: '8654467',
    imageUrl: getBeachImageUrl('hatteras'),
  },
  {
    id: 'hermosa-beach',
    name: 'Hermosa Beach',
    state: 'California',
    latitude: 33.8622,
    longitude: -118.3998,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('hermosa-beach'),
  },
  {
    id: 'hilton-head',
    name: 'Hilton Head',
    state: 'South Carolina',
    latitude: 32.2163,
    longitude: -80.7526,
    stationId: '8670870',
    waterTempStationId: '8670870',
    imageUrl: getBeachImageUrl('hilton-head'),
  },
  {
    id: 'holgate',
    name: 'Holgate',
    state: 'New Jersey',
    latitude: 39.6451,
    longitude: -74.2032,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('holgate'),
  },
  {
    id: 'hollywood-beach',
    name: 'Hollywood Beach',
    state: 'Florida',
    latitude: 26.0112,
    longitude: -80.1495,
    stationId: '8723214',
    waterTempStationId: '8722956',
    imageUrl: getBeachImageUrl('hollywood-beach'),
  },
  {
    id: 'honeymoon-island',
    name: 'Honeymoon Island',
    state: 'Florida',
    latitude: 28.0653,
    longitude: -82.8276,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('honeymoon-island'),
  },
  {
    id: 'huntington',
    name: 'Huntington Beach',
    state: 'California',
    latitude: 33.6595,
    longitude: -118.0000,
    stationId: '9410660',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('huntington'),
  },
  {
    id: 'imperial-beach',
    name: 'Imperial Beach',
    state: 'California',
    latitude: 32.5839,
    longitude: -117.1131,
    stationId: '9410170',
    waterTempStationId: '9410170',
    imageUrl: getBeachImageUrl('imperial-beach'),
  },
  {
    id: 'indian-rocks',
    name: 'Indian Rocks Beach',
    state: 'Florida',
    latitude: 27.8953,
    longitude: -82.8426,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('indian-rocks'),
  },
  {
    id: 'indian-shores',
    name: 'Indian Shores',
    state: 'Florida',
    latitude: 27.8564,
    longitude: -82.8476,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('indian-shores'),
  },
  {
    id: 'islamorada',
    name: 'Islamorada',
    state: 'Florida',
    latitude: 24.9243,
    longitude: -80.6278,
    stationId: '8723970',
    waterTempStationId: '8723970',
    imageUrl: getBeachImageUrl('islamorada'),
  },
  {
    id: 'jones-beach',
    name: 'Jones Beach',
    state: 'New York',
    latitude: 40.5926,
    longitude: -73.5087,
    stationId: '8510560',
    waterTempStationId: '8516945',
    imageUrl: getBeachImageUrl('jones-beach'),
  },
  {
    id: 'kennebunk',
    name: 'Kennebunk Beach',
    state: 'Maine',
    latitude: 43.3617,
    longitude: -70.4767,
    stationId: '8419317',
    waterTempStationId: '8418150',
    imageUrl: getBeachImageUrl('kennebunk'),
  },
  {
    id: 'key-biscayne',
    name: 'Key Biscayne',
    state: 'Florida',
    latitude: 25.6926,
    longitude: -80.1631,
    stationId: '8723214',
    waterTempStationId: '8723214',
    imageUrl: getBeachImageUrl('key-biscayne'),
  },
  {
    id: 'key-west',
    name: 'Key West Beach',
    state: 'Florida',
    latitude: 24.5551,
    longitude: -81.7800,
    stationId: '8724580',
    waterTempStationId: '8724580',
    imageUrl: getBeachImageUrl('key-west'),
  },
  {
    id: 'kiawah-island',
    name: 'Kiawah Island',
    state: 'South Carolina',
    latitude: 32.6085,
    longitude: -80.0842,
    stationId: '8665530',
    waterTempStationId: '8665530',
    imageUrl: getBeachImageUrl('kiawah-island'),
  },
  {
    id: 'kill-devil-hills',
    name: 'Kill Devil Hills',
    state: 'North Carolina',
    latitude: 36.0321,
    longitude: -75.6779,
    stationId: '8651370',
    waterTempStationId: '8651370',
    imageUrl: getBeachImageUrl('kill-devil-hills'),
  },
  {
    id: 'kitty-hawk',
    name: 'Kitty Hawk',
    state: 'North Carolina',
    latitude: 36.0629,
    longitude: -75.7060,
    stationId: '8651370',
    waterTempStationId: '8651370',
    imageUrl: getBeachImageUrl('kitty-hawk'),
  },
  {
    id: 'laguna',
    name: 'Laguna Beach',
    state: 'California',
    latitude: 33.5427,
    longitude: -117.7854,
    stationId: '9410660',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('laguna'),
  },
  {
    id: 'la-jolla',
    name: 'La Jolla Cove',
    state: 'California',
    latitude: 32.8509,
    longitude: -117.2713,
    stationId: '9410170',
    waterTempStationId: '9410230',
    imageUrl: getBeachImageUrl('la-jolla'),
  },
  {
    id: 'lanikai',
    name: 'Lanikai Beach',
    state: 'Hawaii',
    latitude: 21.3981,
    longitude: -157.7165,
    stationId: '1612340',
    waterTempStationId: '1612480',
    imageUrl: getBeachImageUrl('lanikai'),
  },
  {
    id: 'la-push',
    name: 'La Push Beach',
    state: 'Washington',
    latitude: 47.9037,
    longitude: -124.6368,
    stationId: '9442396',
    waterTempStationId: '9442396',
    imageUrl: getBeachImageUrl('la-push'),
  },
  {
    id: 'leo-carrillo',
    name: 'Leo Carrillo Beach',
    state: 'California',
    latitude: 34.0459,
    longitude: -118.9381,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('leo-carrillo'),
  },
  {
    id: 'lido-key',
    name: 'Lido Key',
    state: 'Florida',
    latitude: 27.3153,
    longitude: -82.5826,
    stationId: '8726520',
    waterTempStationId: '8726384',
    imageUrl: getBeachImageUrl('lido-key'),
  },
  {
    id: 'lincoln-city',
    name: 'Lincoln City',
    state: 'Oregon',
    latitude: 44.9579,
    longitude: -124.0179,
    stationId: '9435380',
    waterTempStationId: '9435380',
    imageUrl: getBeachImageUrl('lincoln-city'),
  },
  {
    id: 'long-beach-island',
    name: 'Long Beach Island',
    state: 'New Jersey',
    latitude: 39.6451,
    longitude: -74.1932,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('long-beach-island'),
  },
  {
    id: 'long-beach-peninsula',
    name: 'Long Beach Peninsula',
    state: 'Washington',
    latitude: 46.3523,
    longitude: -124.0540,
    stationId: '9440910',
    waterTempStationId: '9441102',
    imageUrl: getBeachImageUrl('long-beach-peninsula'),
  },
  {
    id: 'longboat-key',
    name: 'Longboat Key',
    state: 'Florida',
    latitude: 27.4103,
    longitude: -82.6626,
    stationId: '8726520',
    waterTempStationId: '8726384',
    imageUrl: getBeachImageUrl('longboat-key'),
  },
  {
    id: 'long-branch',
    name: 'Long Branch',
    state: 'New Jersey',
    latitude: 40.3043,
    longitude: -73.9923,
    stationId: '8531680',
    waterTempStationId: '8531680',
    imageUrl: getBeachImageUrl('long-branch'),
  },
  {
    id: 'loveladies',
    name: 'Loveladies',
    state: 'New Jersey',
    latitude: 39.7043,
    longitude: -74.1760,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('loveladies'),
  },
  {
    id: 'madeira-beach',
    name: 'Madeira Beach',
    state: 'Florida',
    latitude: 27.7970,
    longitude: -82.7976,
    stationId: '8726520',
    waterTempStationId: '8726520',
    imageUrl: getBeachImageUrl('madeira-beach'),
  },
  {
    id: 'malibu',
    name: 'Malibu Beach',
    state: 'California',
    latitude: 34.0259,
    longitude: -118.7798,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('malibu'),
  },
  {
    id: 'manasquan',
    name: 'Manasquan',
    state: 'New Jersey',
    latitude: 40.1168,
    longitude: -74.0365,
    stationId: '8531680',
    waterTempStationId: '8531680',
    imageUrl: getBeachImageUrl('manasquan'),
  },
  {
    id: 'manhattan-beach',
    name: 'Manhattan Beach',
    state: 'California',
    latitude: 33.8847,
    longitude: -118.4109,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('manhattan-beach'),
  },
  {
    id: 'manhattan-state-beach',
    name: 'Manhattan State Beach',
    state: 'California',
    latitude: 33.8847,
    longitude: -118.4109,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('manhattan-state-beach'),
  },
  {
    id: 'manzanita',
    name: 'Manzanita Beach',
    state: 'Oregon',
    latitude: 45.7179,
    longitude: -123.9340,
    stationId: '9435380',
    waterTempStationId: '9440422',
    imageUrl: getBeachImageUrl('manzanita'),
  },
  {
    id: 'marathon',
    name: 'Marathon',
    state: 'Florida',
    latitude: 24.7137,
    longitude: -81.0865,
    stationId: '8723970',
    waterTempStationId: '8723970',
    imageUrl: getBeachImageUrl('marathon'),
  },
  {
    id: 'marco-island',
    name: 'Marco Island',
    state: 'Florida',
    latitude: 25.9412,
    longitude: -81.7187,
    stationId: '8725110',
    waterTempStationId: '8725520',
    imageUrl: getBeachImageUrl('marco-island'),
  },
  {
    id: 'marthas-vineyard',
    name: "Martha's Vineyard",
    state: 'Massachusetts',
    latitude: 41.3888,
    longitude: -70.6189,
    stationId: '8447930',
    waterTempStationId: '8447930',
    imageUrl: getBeachImageUrl('marthas-vineyard'),
  },
  {
    id: 'matagorda',
    name: 'Matagorda Beach',
    state: 'Texas',
    latitude: 28.6889,
    longitude: -95.9688,
    stationId: '8773259',
    waterTempStationId: '8773146',
    imageUrl: getBeachImageUrl('matagorda'),
  },
  {
    id: 'mendocino',
    name: 'Mendocino',
    state: 'California',
    latitude: 39.3077,
    longitude: -123.7994,
    stationId: '9416841',
    waterTempStationId: '9416841',
    imageUrl: getBeachImageUrl('mendocino'),
  },
  {
    id: 'mission-beach',
    name: 'Mission Beach',
    state: 'California',
    latitude: 32.7701,
    longitude: -117.2528,
    stationId: '9410170',
    waterTempStationId: '9410170',
    imageUrl: getBeachImageUrl('mission-beach'),
  },
  {
    id: 'montauk',
    name: 'Montauk',
    state: 'New York',
    latitude: 41.0485,
    longitude: -71.9579,
    stationId: '8510560',
    waterTempStationId: '8510560',
    imageUrl: getBeachImageUrl('montauk'),
  },
  {
    id: 'monterey',
    name: 'Monterey Bay',
    state: 'California',
    latitude: 36.6002,
    longitude: -121.8947,
    stationId: '9413450',
    waterTempStationId: '9413450',
    imageUrl: getBeachImageUrl('monterey'),
  },
  {
    id: 'mustang-island',
    name: 'Mustang Island',
    state: 'Texas',
    latitude: 27.6253,
    longitude: -97.2169,
    stationId: '8775870',
    waterTempStationId: '8775792',
    imageUrl: getBeachImageUrl('mustang-island'),
  },
  {
    id: 'nags-head',
    name: 'Nags Head',
    state: 'North Carolina',
    latitude: 35.9571,
    longitude: -75.6240,
    stationId: '8652587',
    waterTempStationId: '8652587',
    imageUrl: getBeachImageUrl('nags-head'),
  },
  {
    id: 'nantucket',
    name: 'Nantucket',
    state: 'Massachusetts',
    latitude: 41.2835,
    longitude: -70.0995,
    stationId: '8449130',
    waterTempStationId: '8449130',
    imageUrl: getBeachImageUrl('nantucket'),
  },
  {
    id: 'naples',
    name: 'Naples Beach',
    state: 'Florida',
    latitude: 26.1420,
    longitude: -81.7948,
    stationId: '8725110',
    waterTempStationId: '8725520',
    imageUrl: getBeachImageUrl('naples'),
  },
  {
    id: 'narragansett',
    name: 'Narragansett Beach',
    state: 'Rhode Island',
    latitude: 41.4501,
    longitude: -71.4662,
    stationId: '8452660',
    waterTempStationId: '8452660',
    imageUrl: getBeachImageUrl('narragansett'),
  },
  {
    id: 'new-smyrna',
    name: 'New Smyrna Beach',
    state: 'Florida',
    latitude: 29.0258,
    longitude: -80.9270,
    stationId: '8721164',
    waterTempStationId: '8721604',
    imageUrl: getBeachImageUrl('new-smyrna'),
  },
  {
    id: 'newport-beach-ca',
    name: 'Newport Beach',
    state: 'California',
    latitude: 33.6189,
    longitude: -117.9289,
    stationId: '9410660',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('newport-beach-ca'),
  },
  {
    id: 'newport-beach-or',
    name: 'Newport Beach OR',
    state: 'Oregon',
    latitude: 44.6368,
    longitude: -124.0529,
    stationId: '9435380',
    waterTempStationId: '9435380',
    imageUrl: getBeachImageUrl('newport-beach-or'),
  },
  {
    id: 'newport-beach-ri',
    name: 'Newport Beach',
    state: 'Rhode Island',
    latitude: 41.4901,
    longitude: -71.3128,
    stationId: '8452660',
    waterTempStationId: '8452660',
    imageUrl: getBeachImageUrl('newport-beach-ri'),
  },
  {
    id: 'ocean-beach',
    name: 'Ocean Beach',
    state: 'California',
    latitude: 32.7533,
    longitude: -117.2528,
    stationId: '9410170',
    waterTempStationId: '9410170',
    imageUrl: getBeachImageUrl('ocean-beach'),
  },
  {
    id: 'ocean-city-md',
    name: 'Ocean City',
    state: 'Maryland',
    latitude: 38.3365,
    longitude: -75.0849,
    stationId: '8570283',
    waterTempStationId: '8570283',
    imageUrl: getBeachImageUrl('ocean-city-md'),
  },
  {
    id: 'ocean-city-nj',
    name: 'Ocean City Boardwalk',
    state: 'New Jersey',
    latitude: 39.2776,
    longitude: -74.5746,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('ocean-city-nj'),
  },
  {
    id: 'ocean-shores',
    name: 'Ocean Shores',
    state: 'Washington',
    latitude: 46.9737,
    longitude: -124.1568,
    stationId: '9441102',
    waterTempStationId: '9441102',
    imageUrl: getBeachImageUrl('ocean-shores'),
  },
  {
    id: 'ogunquit',
    name: 'Ogunquit Beach',
    state: 'Maine',
    latitude: 43.2490,
    longitude: -70.5989,
    stationId: '8419317',
    waterTempStationId: '8419870',
    imageUrl: getBeachImageUrl('ogunquit'),
  },
  {
    id: 'old-orchard',
    name: 'Old Orchard Beach',
    state: 'Maine',
    latitude: 43.5170,
    longitude: -70.3770,
    stationId: '8418150',
    waterTempStationId: '8418150',
    imageUrl: getBeachImageUrl('old-orchard'),
  },
  {
    id: 'orange-beach',
    name: 'Orange Beach',
    state: 'Alabama',
    latitude: 30.2940,
    longitude: -87.5711,
    stationId: '8735180',
    waterTempStationId: '8729840',
    imageUrl: getBeachImageUrl('orange-beach'),
  },
  {
    id: 'orleans',
    name: 'Orleans',
    state: 'Massachusetts',
    latitude: 41.7901,
    longitude: -69.9897,
    stationId: '8447930',
    waterTempStationId: '8449130',
    imageUrl: getBeachImageUrl('orleans'),
  },
  {
    id: 'ormond-beach',
    name: 'Ormond Beach',
    state: 'Florida',
    latitude: 29.2858,
    longitude: -81.0559,
    stationId: '8721164',
    waterTempStationId: '8721604',
    imageUrl: getBeachImageUrl('ormond-beach'),
  },
  {
    id: 'pacific-beach',
    name: 'Pacific Beach',
    state: 'California',
    latitude: 32.7964,
    longitude: -117.2328,
    stationId: '9410170',
    waterTempStationId: '9410230',
    imageUrl: getBeachImageUrl('pacific-beach'),
  },
  {
    id: 'pacific-city',
    name: 'Pacific City',
    state: 'Oregon',
    latitude: 45.2029,
    longitude: -123.9629,
    stationId: '9435380',
    waterTempStationId: '9435380',
    imageUrl: getBeachImageUrl('pacific-city'),
  },
  {
    id: 'padre-island',
    name: 'Padre Island',
    state: 'Texas',
    latitude: 27.5858,
    longitude: -97.2169,
    stationId: '8775870',
    waterTempStationId: '8775792',
    imageUrl: getBeachImageUrl('padre-island'),
  },
  {
    id: 'panama-city',
    name: 'Panama City Beach',
    state: 'Florida',
    latitude: 30.1766,
    longitude: -85.8055,
    stationId: '8729108',
    waterTempStationId: '8729210',
    imageUrl: getBeachImageUrl('panama-city'),
  },
  {
    id: 'pass-a-grille',
    name: 'Pass-a-Grille Beach',
    state: 'Florida',
    latitude: 27.6953,
    longitude: -82.7376,
    stationId: '8726520',
    waterTempStationId: '8726520',
    imageUrl: getBeachImageUrl('pass-a-grille'),
  },
  {
    id: 'pismo-beach',
    name: 'Pismo Beach',
    state: 'California',
    latitude: 35.1428,
    longitude: -120.6413,
    stationId: '9412110',
    waterTempStationId: '9413450',
    imageUrl: getBeachImageUrl('pismo-beach'),
  },
  {
    id: 'plum-island',
    name: 'Plum Island',
    state: 'Massachusetts',
    latitude: 42.8151,
    longitude: -70.8198,
    stationId: '8443970',
    waterTempStationId: '8419870',
    imageUrl: getBeachImageUrl('plum-island'),
  },
  {
    id: 'point-dume',
    name: 'Point Dume',
    state: 'California',
    latitude: 34.0059,
    longitude: -118.8081,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('point-dume'),
  },
  {
    id: 'point-pleasant',
    name: 'Point Pleasant',
    state: 'New Jersey',
    latitude: 40.0918,
    longitude: -74.0468,
    stationId: '8531680',
    waterTempStationId: '8531680',
    imageUrl: getBeachImageUrl('point-pleasant'),
  },
  {
    id: 'pompano-beach',
    name: 'Pompano Beach',
    state: 'Florida',
    latitude: 26.2379,
    longitude: -80.1248,
    stationId: '8722670',
    waterTempStationId: '8722956',
    imageUrl: getBeachImageUrl('pompano-beach'),
  },
  {
    id: 'port-arthur',
    name: 'Port Arthur Beach',
    state: 'Texas',
    latitude: 29.8849,
    longitude: -93.9300,
    stationId: '8770822',
    waterTempStationId: '8770475',
    imageUrl: getBeachImageUrl('port-arthur'),
  },
  {
    id: 'port-lavaca',
    name: 'Port Lavaca Beach',
    state: 'Texas',
    latitude: 28.6150,
    longitude: -96.6300,
    stationId: '8773259',
    waterTempStationId: '8773259',
    imageUrl: getBeachImageUrl('port-lavaca'),
  },
  {
    id: 'provincetown',
    name: 'Provincetown',
    state: 'Massachusetts',
    latitude: 42.0526,
    longitude: -70.1710,
    stationId: '8446121',
    waterTempStationId: '8447930',
    imageUrl: getBeachImageUrl('provincetown'),
  },
  {
    id: 'redington-beach',
    name: 'Redington Beach',
    state: 'Florida',
    latitude: 27.8153,
    longitude: -82.8176,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('redington-beach'),
  },
  {
    id: 'redington-shores',
    name: 'Redington Shores',
    state: 'Florida',
    latitude: 27.8253,
    longitude: -82.8276,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('redington-shores'),
  },
  {
    id: 'redondo-beach',
    name: 'Redondo Beach',
    state: 'California',
    latitude: 33.8492,
    longitude: -118.3892,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('redondo-beach'),
  },
  {
    id: 'rehoboth',
    name: 'Rehoboth Beach',
    state: 'Delaware',
    latitude: 38.7210,
    longitude: -75.0760,
    stationId: '8557380',
    waterTempStationId: '8557380',
    imageUrl: getBeachImageUrl('rehoboth'),
  },
  {
    id: 'rialto-beach',
    name: 'Rialto Beach',
    state: 'Washington',
    latitude: 47.9204,
    longitude: -124.6368,
    stationId: '9442396',
    waterTempStationId: '9442396',
    imageUrl: getBeachImageUrl('rialto-beach'),
  },
  {
    id: 'rockport',
    name: 'Rockport Beach',
    state: 'Texas',
    latitude: 28.0219,
    longitude: -97.0544,
    stationId: '8774770',
    waterTempStationId: '8774770',
    imageUrl: getBeachImageUrl('rockport'),
  },
  {
    id: 'rodanthe',
    name: 'Rodanthe',
    state: 'North Carolina',
    latitude: 35.5932,
    longitude: -75.4663,
    stationId: '8654467',
    waterTempStationId: '8652587',
    imageUrl: getBeachImageUrl('rodanthe'),
  },
  {
    id: 'rye-beach',
    name: 'Rye Beach',
    state: 'New Hampshire',
    latitude: 43.0101,
    longitude: -70.7709,
    stationId: '8423898',
    waterTempStationId: '8419870',
    imageUrl: getBeachImageUrl('rye-beach'),
  },
  {
    id: 'salisbury-beach',
    name: 'Salisbury Beach',
    state: 'Massachusetts',
    latitude: 42.8376,
    longitude: -70.8103,
    stationId: '8443970',
    waterTempStationId: '8419870',
    imageUrl: getBeachImageUrl('salisbury-beach'),
  },
  {
    id: 'salvo',
    name: 'Salvo',
    state: 'North Carolina',
    latitude: 35.5432,
    longitude: -75.4763,
    stationId: '8654467',
    waterTempStationId: '8652587',
    imageUrl: getBeachImageUrl('salvo'),
  },
  {
    id: 'san-clemente',
    name: 'San Clemente',
    state: 'California',
    latitude: 33.4270,
    longitude: -117.6120,
    stationId: '9410660',
    waterTempStationId: '9410230',
    imageUrl: getBeachImageUrl('san-clemente'),
  },
  {
    id: 'sanibel',
    name: 'Sanibel Island',
    state: 'Florida',
    latitude: 26.4487,
    longitude: -82.1126,
    stationId: '8725110',
    waterTempStationId: '8725520',
    imageUrl: getBeachImageUrl('sanibel'),
  },
  {
    id: 'sea-isle-city',
    name: 'Sea Isle City',
    state: 'New Jersey',
    latitude: 39.1532,
    longitude: -74.6932,
    stationId: '8536110',
    waterTempStationId: '8536110',
    imageUrl: getBeachImageUrl('sea-isle-city'),
  },
  {
    id: 'seaside-beach',
    name: 'Seaside Beach',
    state: 'Oregon',
    latitude: 45.9932,
    longitude: -123.9226,
    stationId: '9435380',
    waterTempStationId: '9440422',
    imageUrl: getBeachImageUrl('seaside-beach'),
  },
  {
    id: 'seaside-heights',
    name: 'Seaside Heights',
    state: 'New Jersey',
    latitude: 39.9443,
    longitude: -74.0726,
    stationId: '8531680',
    waterTempStationId: '8531680',
    imageUrl: getBeachImageUrl('seaside-heights'),
  },
  {
    id: 'ship-bottom',
    name: 'Ship Bottom',
    state: 'New Jersey',
    latitude: 39.6451,
    longitude: -74.1832,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('ship-bottom'),
  },
  {
    id: 'siesta-key',
    name: 'Siesta Key Beach',
    state: 'Florida',
    latitude: 27.2639,
    longitude: -82.5431,
    stationId: '8726520',
    waterTempStationId: '8726384',
    imageUrl: getBeachImageUrl('siesta-key'),
  },
  {
    id: 'solana-beach',
    name: 'Solana Beach',
    state: 'California',
    latitude: 32.9911,
    longitude: -117.2712,
    stationId: '9410170',
    waterTempStationId: '9410230',
    imageUrl: getBeachImageUrl('solana-beach'),
  },
  {
    id: 'south-beach',
    name: 'South Beach',
    state: 'Florida',
    latitude: 25.7907,
    longitude: -80.1300,
    stationId: '8723214',
    waterTempStationId: '8723214',
    imageUrl: getBeachImageUrl('south-beach'),
  },
  {
    id: 'southern-shores',
    name: 'Southern Shores',
    state: 'North Carolina',
    latitude: 36.1293,
    longitude: -75.7360,
    stationId: '8651370',
    waterTempStationId: '8651370',
    imageUrl: getBeachImageUrl('southern-shores'),
  },
  {
    id: 'south-padre',
    name: 'South Padre Island',
    state: 'Texas',
    latitude: 26.1118,
    longitude: -97.1669,
    stationId: '8779770',
    waterTempStationId: '8779748',
    imageUrl: getBeachImageUrl('south-padre'),
  },
  {
    id: 'spring-lake',
    name: 'Spring Lake',
    state: 'New Jersey',
    latitude: 40.1532,
    longitude: -74.0282,
    stationId: '8531680',
    waterTempStationId: '8531680',
    imageUrl: getBeachImageUrl('spring-lake'),
  },
  {
    id: 'st-augustine',
    name: 'St. Augustine Beach',
    state: 'Florida',
    latitude: 29.8572,
    longitude: -81.2650,
    stationId: '8720030',
    waterTempStationId: '8720218',
    imageUrl: getBeachImageUrl('st-augustine'),
  },
  {
    id: 'stinson-beach',
    name: 'Stinson Beach',
    state: 'California',
    latitude: 37.9002,
    longitude: -122.6433,
    stationId: '9414290',
    waterTempStationId: '9414863',
    imageUrl: getBeachImageUrl('stinson-beach'),
  },
  {
    id: 'stone-harbor',
    name: 'Stone Harbor',
    state: 'New Jersey',
    latitude: 39.0507,
    longitude: -74.7596,
    stationId: '8536110',
    waterTempStationId: '8536110',
    imageUrl: getBeachImageUrl('stone-harbor'),
  },
  {
    id: 'st-pete-beach',
    name: 'St. Pete Beach',
    state: 'Florida',
    latitude: 27.7253,
    longitude: -82.7426,
    stationId: '8726520',
    waterTempStationId: '8726520',
    imageUrl: getBeachImageUrl('st-pete-beach'),
  },
  {
    id: 'sunny-isles',
    name: 'Sunny Isles Beach',
    state: 'Florida',
    latitude: 25.9423,
    longitude: -80.1234,
    stationId: '8723214',
    waterTempStationId: '8722956',
    imageUrl: getBeachImageUrl('sunny-isles'),
  },
  {
    id: 'surf-city',
    name: 'Surf City',
    state: 'New Jersey',
    latitude: 39.6618,
    longitude: -74.1660,
    stationId: '8534720',
    waterTempStationId: '8534720',
    imageUrl: getBeachImageUrl('surf-city'),
  },
  {
    id: 'surfside-beach',
    name: 'Surfside Beach',
    state: 'Texas',
    latitude: 28.9447,
    longitude: -95.2899,
    stationId: '8772447',
    waterTempStationId: '8772471',
    imageUrl: getBeachImageUrl('surfside-beach'),
  },
  {
    id: 'tarpon-springs',
    name: 'Tarpon Springs Beach',
    state: 'Florida',
    latitude: 28.1461,
    longitude: -82.7568,
    stationId: '8726520',
    waterTempStationId: '8726724',
    imageUrl: getBeachImageUrl('tarpon-springs'),
  },
  {
    id: 'the-hamptons',
    name: 'The Hamptons',
    state: 'New York',
    latitude: 40.9629,
    longitude: -72.1851,
    stationId: '8510560',
    waterTempStationId: '8510560',
    imageUrl: getBeachImageUrl('the-hamptons'),
  },
  {
    id: 'torrey-pines',
    name: 'Torrey Pines',
    state: 'California',
    latitude: 32.9278,
    longitude: -117.2542,
    stationId: '9410170',
    waterTempStationId: '9410230',
    imageUrl: getBeachImageUrl('torrey-pines'),
  },
  {
    id: 'treasure-island',
    name: 'Treasure Island',
    state: 'Florida',
    latitude: 27.7692,
    longitude: -82.7693,
    stationId: '8726520',
    waterTempStationId: '8726520',
    imageUrl: getBeachImageUrl('treasure-island'),
  },
  {
    id: 'truro',
    name: 'Truro',
    state: 'Massachusetts',
    latitude: 41.9901,
    longitude: -70.0597,
    stationId: '8447930',
    waterTempStationId: '8447930',
    imageUrl: getBeachImageUrl('truro'),
  },
  {
    id: 'tybee-island',
    name: 'Tybee Island',
    state: 'Georgia',
    latitude: 32.0002,
    longitude: -80.8454,
    stationId: '8670870',
    waterTempStationId: '8670870',
    imageUrl: getBeachImageUrl('tybee-island'),
  },
  {
    id: 'venice-fl',
    name: 'Venice Beach FL',
    state: 'Florida',
    latitude: 27.0998,
    longitude: -82.4543,
    stationId: '8726520',
    waterTempStationId: '8726384',
    imageUrl: getBeachImageUrl('venice-fl'),
  },
  {
    id: 'venice',
    name: 'Venice Beach',
    state: 'California',
    latitude: 33.9850,
    longitude: -118.4695,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('venice'),
  },
  {
    id: 'virginia-beach',
    name: 'Virginia Beach',
    state: 'Virginia',
    latitude: 36.8529,
    longitude: -75.9780,
    stationId: '8638610',
    waterTempStationId: '8639348',
    imageUrl: getBeachImageUrl('virginia-beach'),
  },
  {
    id: 'waves',
    name: 'Waves',
    state: 'North Carolina',
    latitude: 35.5532,
    longitude: -75.4663,
    stationId: '8654467',
    waterTempStationId: '8652587',
    imageUrl: getBeachImageUrl('waves'),
  },
  {
    id: 'wellfleet',
    name: 'Wellfleet',
    state: 'Massachusetts',
    latitude: 41.9376,
    longitude: -70.0328,
    stationId: '8447930',
    waterTempStationId: '8447930',
    imageUrl: getBeachImageUrl('wellfleet'),
  },
  {
    id: 'wells-beach',
    name: 'Wells Beach',
    state: 'Maine',
    latitude: 43.3220,
    longitude: -70.5798,
    stationId: '8419317',
    waterTempStationId: '8419870',
    imageUrl: getBeachImageUrl('wells-beach'),
  },
  {
    id: 'wildwood',
    name: 'Wildwood',
    state: 'New Jersey',
    latitude: 38.9918,
    longitude: -74.8149,
    stationId: '8536110',
    waterTempStationId: '8536110',
    imageUrl: getBeachImageUrl('wildwood'),
  },
  {
    id: 'york-beach',
    name: 'York Beach',
    state: 'Maine',
    latitude: 43.1701,
    longitude: -70.6098,
    stationId: '8419317',
    waterTempStationId: '8419870',
    imageUrl: getBeachImageUrl('york-beach'),
  },
  {
    id: 'zuma-beach',
    name: 'Zuma Beach',
    state: 'California',
    latitude: 34.0159,
    longitude: -118.8231,
    stationId: '9410840',
    waterTempStationId: '9410840',
    imageUrl: getBeachImageUrl('zuma-beach'),
  },
];

/**
 * Attaches the live-camera link and direct/nearby tag to a beach from
 * {@link CAMERA_DATA}. Beaches without an entry are returned unchanged (no cam).
 */
function applyCameraData(beach: Beach): Beach {
  const cam = CAMERA_DATA[beach.id];
  if (!cam) {
    return beach;
  }
  return { ...beach, cameraUrl: cam.url, cameraType: cam.type };
}

export const POPULAR_BEACHES: Beach[] = POPULAR_BEACHES_BASE.map(applyCameraData);
export const ALL_BEACHES: Beach[] = ALL_BEACHES_BASE.map(applyCameraData);
